### ISSUE TITLE
Te felicito, código muy limpio y ordenado

### ISSUE THREAD

**Issue by vicenlu** [adaldin/itacademy#1]
En cuanto al formato, lo único que he visto es que no está del todo uniforme.

Los divs arriba los cierras en una nueva línea, en cambio aquí los cierras inline.

https://github.com/adaldin/itacademy/blob/cba68d6cf473d4763d49e590024d138a485f9d94/sprint-1/nivell-1/index.html#L31

**Comment by adaldin** [comment]
Gracias!!
