### ISSUE TITLE
Te felicito, es la mejor entrega del sprint 3 que he tenido!!

### ISSUE THREAD

**Issue by itacademyReact** [adaldin/itacademy#3]
Hay alumnos que han hecho muy bien la lógica, pero tu también has trabajado la parte visual.

¡Sigue así, tienes mucho potencial!! 

https://github.com/adaldin/itacademy/blob/c8453a29b4c7922203703921028d4ffeea484d18/shopping-app-js/js/shop.js#L255

**Comment by adaldin** [comment]
:) Gracias Luis!!
