### ISSUE TITLE
En pruebas técnicas o proyectos reales procuraría no dejar tantas líneas en blanco

### ISSUE THREAD

**Issue by itacademyReact** [adaldin/itacademy#4]
Cuida el formato, cuesta poco y garantizas que no pierdes puntos por eso.

Prettier funciona muy bien para dar formato automático:
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

https://github.com/adaldin/itacademy/blob/c8453a29b4c7922203703921028d4ffeea484d18/shopping-app-js/js/shop.js#L228

**Comment by adaldin** [comment]
Si, y mira que me lo has dicho en el anterior. He tenido un problema con el formateador que tenía instalado y he hecho todo yo. Paso a instalar Prettier ahora mismo!
