### ISSUE TITLE
Está genial cómo has organizado tu repo de IT Academy, aunque si me pusieses cada entrega en un repo podría hacerte auditorías de código

### ISSUE THREAD

**Issue by itacademyReact** [adaldin/itacademy#5]
Estoy comenzando a hacer auditorías de código, pero si tengo las entregas en un mismo repo sale el resultado global y es más difícil de analizar.

Estaría genial que en el sprint 5 o en la parte de React tuvieses un repo por entrega. Así también creas un portfolio más completo, ya que esos proyectos son más interesantes y puede tener valor ponerlos por separado.

https://github.com/adaldin/itacademy/blob/c8453a29b4c7922203703921028d4ffeea484d18/shopping-app-js/index.html#L2

**Comment by adaldin** [comment]
Vale, perfect. Lo pensé así en un principio per por algún motivo pensaba que iba a ser un caos si tenía todo separado a nivel corrección. Empezaré a separarlos desde el 5, e iré pasando todos a repos individuales. Gracias por la sugerencia!
