### ISSUE TITLE
Creo que no devuelves solo 20 películas

### ISSUE THREAD

**Issue by itacademyReact** [adaldin/itacademy#8]
Te proporciono solución alternativa:

`const orderAlphabetically = (movies) => [...movies.map((movie) => movie.title)].sort().slice(0, 20);`

https://github.com/adaldin/itacademy/blob/e3b0ac618db855030021eed1bbd0364438ba95a0/sprint-4/src/films.js#L19

**Comment by adaldin** [comment]
Acá tengo una duda. Está marcada la linea 19 del código, pero puede ser que sea la 36? Y si es la función de order alfabético, al final genero un slice y lo guardo en una variable que es lo que pongo en el return. Ahí devuelve los primeros 20. Es esto lo que pedía el ejercicio? o lo he interpretado mal?
