### ISSUE TITLE
Está bien resuelto, pero te proporciono solución alternativa

### ISSUE THREAD

**Issue by itacademyReact** [adaldin/itacademy#9]
`const orderByYear = (movies) => [...movies.sort((a, b) => a.year > b.year ? 1 : -1)];
`
https://github.com/adaldin/itacademy/blob/e3b0ac618db855030021eed1bbd0364438ba95a0/sprint-4/src/films.js#L57

**Comment by adaldin** [comment]
Vale, perfecto, mucho más sintético y simple
